# Generated by Django 5.0 on 2024-01-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='quizzy_app_customuser',
        ),
    ]
