# Generated by Django 4.0 on 2023-12-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0007_remove_comment_dislikes_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
