# Generated by Django 4.0 on 2024-01-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0011_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
