# Generated by Django 5.0 on 2024-01-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0012_remove_comment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
