# Generated by Django 5.0 on 2024-01-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0013_delete_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='post',
        ),
    ]
