# Generated by Django 5.0 on 2024-01-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0014_remove_search_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
