# Generated by Django 5.0 on 2024-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0016_delete_search_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
